# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HLStockLine' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking', '3.2.1'
  pod 'Masonry', '1.1.0'
  pod 'SDWebImage'
  pod 'SDCycleScrollView','1.75'
  pod 'MJRefresh'
  pod 'WXHTextBoxField', :git => 'https://github.com/568071718/xh_textfield.git', :tag => '0.0.1'
  pod 'WMPageController', '~> 2.4.0'
  pod 'YYCache', '~> 1.0.4'

  # Pods for OrangeTaoJin

end
